"""
REST API — /api/*
Swagger UI at /api/docs  (auto-generated by flask-restx)
"""
from flask import request
from flask_restx import Api, Namespace, Resource, fields

from src.ml_engine import all_symptoms, df, get_disease_symptoms, matcher, predict_disease

# ── Api object (init_app called from app.py) ───────────────────────────────────
api = Api(
    version='1.0',
    title='GenZ AI Healthcare Assistant API',
    description=(
        'Disease prediction from symptoms using a Random Forest classifier '
        '(99.4% CV accuracy) trained on 441 samples across 72 diseases. '
        'Symptom matching uses TF-IDF with character n-grams for typo tolerance, '
        'upgradeable to sentence-transformers semantic search.'
    ),
    doc='/api/docs',
    prefix='/api',
)

# ── Namespaces ─────────────────────────────────────────────────────────────────
system_ns    = Namespace('system',    description='Health and status checks')
reference_ns = Namespace('reference', description='Symptom and disease reference data')
predict_ns   = Namespace('predict',   description='Disease prediction')

api.add_namespace(system_ns)
api.add_namespace(reference_ns)
api.add_namespace(predict_ns)

# ── Models (for Swagger request/response docs) ─────────────────────────────────
predict_input = predict_ns.model('PredictInput', {
    'symptoms': fields.List(
        fields.String,
        required=True,
        description='List of symptom descriptions (free text OK)',
        example=['fever', 'headache', 'skin rash'],
    ),
})

predict_output = predict_ns.model('PredictOutput', {
    'disease':          fields.String(description='Predicted disease name'),
    'confidence':       fields.Float(description='Model confidence (0–1)'),
    'symptoms_matched': fields.List(fields.String, description='Canonical symptom names used'),
    'disclaimer':       fields.String,
})

match_input = predict_ns.model('MatchInput', {
    'text':  fields.String(required=True, description='Free-text symptom', example='joint pian'),
    'top_k': fields.Integer(description='Number of candidates to return', default=3),
})

match_output = predict_ns.model('MatchOutput', {
    'input':   fields.String,
    'matches': fields.List(fields.String, description='Closest canonical symptoms'),
})

# ── System ─────────────────────────────────────────────────────────────────────
@system_ns.route('/health')
class Health(Resource):
    def get(self):
        """Service health check"""
        from src.ml_engine import clf
        return {
            'status': 'ok',
            'service': 'GenZ AI Healthcare Assistant',
            'model_loaded': clf is not None,
            'symptom_matcher_backend': matcher.backend_name,
        }


# ── Reference ──────────────────────────────────────────────────────────────────
@reference_ns.route('/symptoms')
class Symptoms(Resource):
    @reference_ns.doc(params={'q': 'Optional search filter'})
    def get(self):
        """List all 318 canonical symptom names"""
        q = request.args.get('q', '').lower()
        filtered = [s for s in all_symptoms if q in s] if q else all_symptoms
        return {'symptoms': filtered, 'count': len(filtered)}


@reference_ns.route('/diseases')
class Diseases(Resource):
    @reference_ns.doc(params={'q': 'Optional search filter'})
    def get(self):
        """List all 72 known diseases"""
        diseases = sorted(df['Disease'].unique().tolist())
        q = request.args.get('q', '').lower()
        if q:
            diseases = [d for d in diseases if q in d.lower()]
        return {'diseases': diseases, 'count': len(diseases)}


@reference_ns.route('/diseases/<path:disease_name>/symptoms')
@reference_ns.doc(params={'disease_name': 'Disease name (partial match supported)'})
class DiseaseSymptoms(Resource):
    def get(self, disease_name):
        """Get known symptoms for a specific disease"""
        found, data = get_disease_symptoms(disease_name)
        if not found:
            reference_ns.abort(404, data)
        return {'disease': disease_name, 'symptoms': data, 'count': len(data)}


# ── Prediction ─────────────────────────────────────────────────────────────────
@predict_ns.route('/')
class Predict(Resource):
    @predict_ns.expect(predict_input, validate=True)
    @predict_ns.marshal_with(predict_output)
    def post(self):
        """Predict disease from a list of symptoms"""
        body = request.get_json()
        symptoms = body.get('symptoms', [])
        if not symptoms:
            predict_ns.abort(400, 'Provide a non-empty "symptoms" list')
        result = predict_disease(symptoms)
        result['disclaimer'] = (
            'AI-generated prediction for informational purposes only. '
            'Always consult a qualified medical professional.'
        )
        return result


@predict_ns.route('/match-symptom')
class MatchSymptom(Resource):
    @predict_ns.expect(match_input, validate=True)
    @predict_ns.marshal_with(match_output)
    def post(self):
        """Map free-text input to the closest canonical symptom(s)"""
        body = request.get_json()
        text = body.get('text', '').strip()
        if not text:
            predict_ns.abort(400, 'Provide a "text" field')
        top_k = min(int(body.get('top_k', 3)), 10)
        return {'input': text, 'matches': matcher.match_many(text, top_k=top_k)}
